#!/usr/bin/env node
/**
 * Write `published-schemas.json` — the JSON Schema of every registered contract, plus
 * the version it was published at.
 *
 * This file *is* the baseline the compatibility gate compares against. Committing it,
 * rather than fetching the previous package from a registry, means the gate needs no
 * infrastructure: it works in a fresh CI checkout, in a sparse checkout, and offline.
 *
 * Regenerate with `npm run schemas:snapshot`, which is part of `npm run release:prepare`.
 * Regenerating it *without* bumping the version is what the gate is there to catch.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')

const { toJsonSchemas } = await import(join(ROOT, 'dist/index.mjs'))
const { version } = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'))

const snapshot = {
  $comment:
    'Generated by scripts/snapshot.mjs. The baseline for scripts/check-contract-compat.mjs. Do not edit by hand.',
  version,
  schemas: toJsonSchemas(),
}

const out = join(ROOT, 'published-schemas.json')
writeFileSync(out, `${JSON.stringify(snapshot, null, 2)}\n`)

console.log(`wrote published-schemas.json at v${version} (${Object.keys(snapshot.schemas).length} schemas)`)
