import type { AttachmentDeletionReason } from '@horizon/contracts'
import type { Attachment, Owner } from '@/domain/attachment'
import type { RecordReference } from '@/domain/records'

export interface Clock {
  now(): Date
}

/** An owner's key, stored wrapped by the master key; null once erased (ADR 0026). */
export interface OwnerKey {
  readonly owner: Owner
  readonly wrappedKey: string | null
  readonly erasedAt: Date | null
}

/** One removal of stored bytes, kept forever: the retention job's log (Phase 65). */
export interface Removal extends RecordReference {
  readonly attachmentId: string
  readonly reason: AttachmentDeletionReason
  readonly bytes: number
  readonly removedAt: Date
}

export interface AuditRecord {
  readonly actor: string
  readonly action: 'attachment.requested' | 'attachment.deleted' | 'attachment.link-issued'
  readonly attachmentId: string
  readonly occurredAt: Date
  readonly requestId: string | null
  readonly details: Record<string, unknown>
}

export interface OutgoingEvent {
  readonly eventType: string
  readonly occurredAt: Date
  readonly payload: Record<string, unknown>
}

/** Everything one tenant-bound transaction may touch. */
export interface FilesScope {
  readonly attachments: {
    insert(attachment: Attachment): Promise<void>
    find(id: string): Promise<Attachment | null>
    findByKey(idempotencyKey: string): Promise<Attachment | null>
    /** Writes `next` only if the row is still `expected`; false when someone moved it first. */
    replace(expected: Attachment, next: Attachment): Promise<boolean>
    ofRecord(record: RecordReference): Promise<Attachment[]>
    ofOwner(owner: Owner): Promise<Attachment[]>
    /**
     * Rows whose `dueAt` has passed, taken for a while: their `dueAt` moves to `until`, so
     * another worker skips them, and a worker that dies leaves them due again.
     */
    claimDue(now: Date, until: Date, limit: number): Promise<Attachment[]>
  }
  readonly ownerKeys: {
    find(owner: Owner): Promise<OwnerKey | null>
    /** Inserts the key unless one exists, and answers the one that is stored. */
    create(owner: Owner, wrappedKey: string, now: Date): Promise<OwnerKey>
    /** Destroys the key, or records an erased owner never seen before. */
    shred(owner: Owner, now: Date): Promise<void>
  }
  readonly removals: { append(removal: Removal): Promise<void> }
  readonly audit: { append(record: AuditRecord): Promise<void> }
  readonly outbox: { append(event: OutgoingEvent): Promise<void> }
  /** False when this event was already handled. */
  readonly inbox: {
    claim(sourceModule: string, eventId: string, eventType: string): Promise<boolean>
  }
}

export interface FilesStore {
  inTenant<T>(tenantId: string, work: (scope: FilesScope) => Promise<T>): Promise<T>
}

/** Encrypted bytes at rest. Keys are generated by `files`, never taken from a caller. */
export interface ObjectStore {
  put(key: string, bytes: Buffer): Promise<void>
  get(key: string): Promise<Buffer>
  /** Idempotent: removing what is not there succeeds. */
  remove(key: string): Promise<void>
}

export type ScanVerdict =
  | { readonly clean: true }
  | { readonly clean: false; readonly finding: string }

/** The scanner port (ADR 0060). Throwing means "no answer", never "clean". */
export interface Scanner {
  scan(bytes: Buffer): Promise<ScanVerdict>
}

export interface CipherContext {
  readonly tenantId: string
  readonly attachmentId: string
  readonly owner: Owner
}

/** Envelope encryption: a data key per file, wrapped by the owner's key, itself wrapped. */
export interface Envelope {
  newOwnerKey(tenantId: string, owner: Owner): string
  seal(
    wrappedOwnerKey: string,
    context: CipherContext,
    plaintext: Buffer,
  ): { object: Buffer; wrappedDataKey: string }
  /** Throws when anything does not match: the key, the context or the bytes. */
  open(
    wrappedOwnerKey: string,
    context: CipherContext,
    wrappedDataKey: string,
    object: Buffer,
  ): Buffer
}

export function objectKeyOf(tenantId: string, attachmentId: string): string {
  return `attachments/${tenantId}/${attachmentId}`
}

/**
 * The key one upload writes (Phase 92): its own, under the attachment's. Two uploads of
 * one slot would otherwise write the same object, and the one recorded could keep the data
 * key of bytes the other had overwritten.
 */
export function uploadKeyOf(tenantId: string, attachmentId: string, uploadId: string): string {
  return `${objectKeyOf(tenantId, attachmentId)}.${uploadId}`
}
